import { minify as htmlMinifier } from 'html-minifier';
import CleanCSS from 'clean-css';

export type Lang =
  | 'de'
  | 'ru'
  | 'fr'
  | 'en'
  | 'it'
  | 'pt'
  | 'es'
  | 'ja'
  | 'ko'
  | 'zh'
  | 'nl'
  | 'pl'
  | 'cs'
  | 'da'
  | 'et'
  | 'fi'
  | 'lt'
  | 'lv'
  | 'no'
  | 'sl'
  | 'sv'
  | 'tr'
  | 'uk';

export type Locales = { [key in Lang]: { title: string; content: string } };

export const getLang = (locales: Locales): Lang => {
  const htmlLang = document.getElementsByTagName('html')[0].getAttribute('lang');
  const locale = htmlLang?.slice(0, 2) as Lang;
  return locale && locale in locales ? locale : 'en';
};

export const addMarkup = (html: string, ID: string): void => {
  const markup = document.createElement('div');
  markup.id = ID;
  markup.innerHTML = html;
  document.body.appendChild(markup);
};

export const applyLogic = (): void => {
  document.body.style.overflow = 'hidden';
};

export const updateContent = (oldContent: string, newContent: string): string => {
  const separatorStart = '/* Auto Generated Start */';
  const separatorEnd = '/* Auto Generated End */';
  return `${oldContent.substr(0, oldContent.indexOf(separatorStart))}${separatorStart}
${newContent}
  ${oldContent.substr(oldContent.indexOf(separatorEnd))}`;
};

export const minifyHTML = (str: string): string =>
  htmlMinifier(str, {
    collapseWhitespace: true,
    collapseInlineTagWhitespace: true,
    removeAttributeQuotes: true,
    removeComments: true,
    minifyCSS: true,
    minifyJS: true,
    includeAutoGeneratedTags: false,
    quoteCharacter: '"',
  });

export const minifyCSS = (str: string): string => new CleanCSS().minify(str).styles;
